name: Plingdollar
exclude: [etc]
twitter_url: https://twitter.com/willspeak/
twitter_url: https://twitter.com/willspeak/
flickr_url: https://flickr.com/photos/alphaindigo
deviant_url: https://deviantart.com/iwillspeak
instagram_url: https://instagram.com/speakypoo
twitch_url: https://twitch.tv/iwillspeak
url: http://willspeak.me

markdown: kramdown

prose:
  rooturl: "_posts"
  siteurl: "http://willspeak.me/"
  media: "img/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
